name: CI-CD

on:
  push:
    branches: [ main ]

 
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show Env
        run: |
          echo ${{ secrets.DOCKERHUB_USER }}
          echo ${{ secrets.DOCKERHUB_PWD }}
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
